version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "deploy/task-definition.json"
        LoadBalancerInfo:
          ContainerName: "apartment-practice-nginx-rails"
          ContainerPort: 80