version: 0.2
env:
  variables:
    RAILS_ENV: test
    DATABASE_HOST: localhost
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: ""

phases:
  install:
    commands:
      - ruby -v
      - bundle config set path 'vendor/bundle'
      - bundle install --jobs=4 --retry=3
      - service mysql start
      - mysql --version
      - mysql -hlocalhost -uroot -ppassword -P3306 -e "show databases;"
      - ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - yarn install
  build:
    commands:
      - bin/rake db:create db:migrate
      - bundle exec webpack
      - bundle exec rspec
cache:
  paths:
    - "node_modules/**/*"
    - "vendor/bundle/**/*"
