name: RSpec

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - staging

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TZ: Asia/Tokyo
      DATABASE_NAME: apartment_practice_test
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ruby 2.7.2のセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup Database
        run: |
          bundle exec rails db:create db:schema:load --trace

      - name: Exec RSpec
        run: |
          bundle exec rspec --format documentation --force-color --backtrace
